"""Local embeddings, FAISS retrieval and grounded question answering with Gemini.

Embeddings are computed locally with Sentence Transformers (no API call).
The answer is generated by the Google Gemini API.

This module also holds the small LLM helpers (`get_llm`, `run_chain`) that the
summarizer and comparator modules reuse.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_google_genai import ChatGoogleGenerativeAI

import config
from prompts import NOT_FOUND_MESSAGE, RAG_QA_PROMPT

if TYPE_CHECKING:
    from langchain_huggingface import HuggingFaceEmbeddings


# --------------------------------------------------------------------------- #
# Exceptions (all messages are written to be shown directly in Streamlit)
# --------------------------------------------------------------------------- #
class MissingAPIKeyError(RuntimeError):
    """Raised when a Gemini call is attempted without GEMINI_API_KEY."""


class LLMError(RuntimeError):
    """Base class for problems while calling the Gemini API."""


class LLMRateLimitError(LLMError):
    """Gemini free-tier rate limit or quota reached (HTTP 429)."""


class LLMAuthError(LLMError):
    """The Gemini API key was rejected."""


class LLMModelError(LLMError):
    """The configured Gemini model does not exist or is not available."""


class LLMUnavailableError(LLMError):
    """Gemini is temporarily overloaded or down (HTTP 5xx)."""


class LLMConnectionError(LLMError):
    """Network problem or timeout while contacting Gemini."""


class EmbeddingError(RuntimeError):
    """The local embedding model or the FAISS index could not be used."""


# --------------------------------------------------------------------------- #
# Error translation
# --------------------------------------------------------------------------- #
def _shorten(text: str, limit: int = 300) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[:limit].rstrip() + "…"


def _exception_chain(exc: BaseException) -> list[BaseException]:
    chain: list[BaseException] = []
    seen: set[int] = set()
    current: BaseException | None = exc
    while current is not None and id(current) not in seen and len(chain) < 6:
        chain.append(current)
        seen.add(id(current))
        current = current.__cause__ or current.__context__
    return chain


def _status_code(chain: list[BaseException]) -> int | None:
    for error in chain:
        for attr in ("code", "status_code"):
            value = getattr(error, attr, None)
            if isinstance(value, int) and 100 <= value < 600:
                return value
        response_code = getattr(getattr(error, "response", None), "status_code", None)
        if isinstance(response_code, int):
            return response_code
    return None


def _translate_llm_error(exc: Exception) -> Exception:
    """Convert any exception raised by the Gemini call into a friendly one."""
    chain = _exception_chain(exc)
    code = _status_code(chain)
    text = " ".join(str(error) for error in chain).lower()
    detail = _shorten(str(exc))

    if code == 429 or any(
        marker in text
        for marker in ("resource_exhausted", "quota", "rate limit", "rate-limit", "too many requests")
    ):
        return LLMRateLimitError(
            "⏳ Gemini free-tier rate limit or daily quota reached. Wait about a "
            "minute and try again. If it keeps happening, you may have used up "
            "today's free quota; try again tomorrow or set a different "
            f"GEMINI_MODEL in your .env file. (Details: {detail})"
        )
    if code in (401, 403) or any(
        marker in text
        for marker in ("api key not valid", "api_key_invalid", "api key expired", "permission_denied", "unauthenticated")
    ):
        return LLMAuthError(
            "🔑 Gemini rejected the API key (or this key cannot use the Gemini API "
            "from your region/project). Check GEMINI_API_KEY in your .env file, or "
            f"create a new key at https://aistudio.google.com/apikey. (Details: {detail})"
        )
    if code == 404 or any(
        marker in text
        for marker in ("not_found", "no longer available", "is not found", "not supported for generatecontent")
    ):
        return LLMModelError(
            f"🤖 The Gemini model `{config.GEMINI_MODEL}` was not found or is not available "
            "for your key. Set GEMINI_MODEL in your .env file to another free-tier model, "
            f"for example `gemini-3.1-flash-lite`. (Details: {detail})"
        )
    if code in (500, 502, 503, 504) or any(
        marker in text for marker in ("unavailable", "overloaded", "deadline_exceeded", "internal error")
    ):
        return LLMUnavailableError(
            "🛠️ The Gemini service is temporarily overloaded or unavailable. "
            f"Please try again in a few seconds. (Details: {detail})"
        )
    if any(
        marker in text
        for marker in ("timeout", "timed out", "connecterror", "connection", "getaddrinfo", "network")
    ):
        return LLMConnectionError(
            "🌐 Could not reach the Gemini API. Check your internet connection and try again. "
            f"(Details: {detail})"
        )
    return LLMError(f"Gemini request failed: {detail}")


# --------------------------------------------------------------------------- #
# LLM helpers (shared with summarizer.py and comparator.py)
# --------------------------------------------------------------------------- #
def _require_api_key() -> str:
    api_key = config.get_api_key()
    if api_key is None:
        raise MissingAPIKeyError(config.API_KEY_MISSING_MESSAGE)
    return api_key


def get_llm() -> ChatGoogleGenerativeAI:
    """Return the Gemini chat model (called through the Gemini API)."""
    api_key = _require_api_key()
    kwargs: dict = {
        "model": config.GEMINI_MODEL,
        "api_key": api_key,
        "timeout": config.LLM_TIMEOUT_SECONDS,
        "max_retries": config.LLM_MAX_RETRIES,
    }
    # Gemini 3 models should keep their default temperature (see config.py).
    if config.TEMPERATURE is not None:
        kwargs["temperature"] = config.TEMPERATURE
    try:
        return ChatGoogleGenerativeAI(**kwargs)
    except Exception as exc:  # noqa: BLE001
        raise LLMError(f"Could not initialise the Gemini model `{config.GEMINI_MODEL}`: {_shorten(str(exc))}") from exc


_embeddings_cache: dict[tuple[str, str], "HuggingFaceEmbeddings"] = {}


def get_embeddings() -> "HuggingFaceEmbeddings":
    """Return the LOCAL Sentence Transformer embedding model (cached).

    No API request is made when embedding text. The model files are downloaded
    from Hugging Face once, on first use, and cached on your disk.
    """
    cache_key = (config.EMBEDDING_MODEL, config.EMBEDDING_DEVICE)
    cached = _embeddings_cache.get(cache_key)
    if cached is not None:
        return cached

    try:
        from langchain_huggingface import HuggingFaceEmbeddings
    except ImportError as exc:
        raise EmbeddingError(
            "The local embedding packages are not installed. Run: "
            "pip install langchain-huggingface sentence-transformers"
        ) from exc

    try:
        embeddings = HuggingFaceEmbeddings(
            model_name=config.EMBEDDING_MODEL,
            model_kwargs={"device": config.EMBEDDING_DEVICE},
            encode_kwargs={"normalize_embeddings": True, "batch_size": 32},
        )
    except Exception as exc:  # noqa: BLE001
        raise EmbeddingError(
            f"Could not load the local embedding model `{config.EMBEDDING_MODEL}`. "
            "The first run needs an internet connection to download it once "
            f"(about 90 MB). Details: {_shorten(str(exc))}"
        ) from exc

    _embeddings_cache[cache_key] = embeddings
    return embeddings


def _message_text(message) -> str:
    """Extract plain text from a chat message.

    Gemini may return `content` as a string or as a list of content blocks
    (text, thinking, ...). Only the text blocks are kept.
    """
    content = getattr(message, "content", message)
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict) and block.get("type") in (None, "text"):
                text = block.get("text")
                if isinstance(text, str):
                    parts.append(text)
        return "".join(parts)
    return str(content)


def run_chain(prompt: ChatPromptTemplate, inputs: dict) -> str:
    """Run `prompt | gemini` and return the answer as plain text.

    Raises MissingAPIKeyError or an LLMError subclass with a friendly message.
    """
    llm = get_llm()  # raises MissingAPIKeyError if the key is missing
    chain = prompt | llm
    try:
        message = chain.invoke(inputs)
    except Exception as exc:  # noqa: BLE001 - translate every API failure
        raise _translate_llm_error(exc) from exc

    text = _message_text(message).strip()
    if not text:
        raise LLMError(
            "Gemini returned an empty response (it may have been blocked by a "
            "safety filter). Try rephrasing your request."
        )
    return text


# --------------------------------------------------------------------------- #
# Result types
# --------------------------------------------------------------------------- #
@dataclass
class SourceReference:
    index: int        # the [n] number used in the answer
    filename: str
    page: int
    snippet: str


@dataclass
class RAGResult:
    answer: str
    sources: list[SourceReference] = field(default_factory=list)
    found: bool = True


# --------------------------------------------------------------------------- #
# Formatting helpers
# --------------------------------------------------------------------------- #
def _make_snippet(text: str, max_chars: int = 300) -> str:
    text = " ".join(text.split())
    return text if len(text) <= max_chars else text[:max_chars].rstrip() + "…"


def _format_context(documents: list[Document]) -> str:
    blocks = []
    for number, doc in enumerate(documents, start=1):
        source = doc.metadata.get("source", "unknown")
        page = doc.metadata.get("page", "?")
        blocks.append(f"[{number}] (Source: {source}, Page {page})\n{doc.page_content}")
    return "\n\n".join(blocks)


def _format_history(chat_history: list[dict] | None) -> str:
    if not chat_history:
        return "(no previous messages)"
    lines = []
    for message in chat_history[-config.MAX_HISTORY_MESSAGES:]:
        speaker = "User" if message.get("role") == "user" else "Assistant"
        content = " ".join(str(message.get("content", "")).split())
        if len(content) > 600:
            content = content[:600] + "…"
        lines.append(f"{speaker}: {content}")
    return "\n".join(lines)


def _cited_numbers(answer: str) -> set[int]:
    """Find citation numbers such as [1], [2][3] or [1, 2] in the answer."""
    numbers: set[int] = set()
    for group in re.findall(r"\[([\d,\s]+)\]", answer):
        for part in group.split(","):
            part = part.strip()
            if part.isdigit():
                numbers.add(int(part))
    return numbers


# --------------------------------------------------------------------------- #
# RAG pipeline
# --------------------------------------------------------------------------- #
class RAGPipeline:
    """Builds a FAISS index (local embeddings) and answers questions with Gemini."""

    def __init__(self) -> None:
        self.vectorstore: FAISS | None = None
        self.num_chunks: int = 0

    @property
    def is_ready(self) -> bool:
        return self.vectorstore is not None

    def build_index(self, chunks: list[Document]) -> None:
        """Embed all chunks locally and store them in an in-memory FAISS index."""
        valid_chunks = [chunk for chunk in chunks if chunk.page_content and chunk.page_content.strip()]
        if not valid_chunks:
            raise ValueError("There are no text chunks to index.")

        embeddings = get_embeddings()
        try:
            self.vectorstore = FAISS.from_documents(valid_chunks, embeddings)
        except EmbeddingError:
            raise
        except Exception as exc:  # noqa: BLE001
            raise EmbeddingError(
                f"Could not create embeddings / the FAISS index: {_shorten(str(exc))}"
            ) from exc
        self.num_chunks = len(valid_chunks)

    def retrieve(
        self,
        question: str,
        k: int | None = None,
        sources: list[str] | None = None,
    ) -> list[Document]:
        """Return the top-k most similar chunks, optionally limited to some files."""
        if self.vectorstore is None:
            raise RuntimeError("The search index has not been built yet.")
        k = k or config.TOP_K

        search_kwargs: dict = {}
        if sources:
            allowed = set(sources)
            search_kwargs["filter"] = lambda metadata: metadata.get("source") in allowed
            search_kwargs["fetch_k"] = max(self.num_chunks, k)
        try:
            return self.vectorstore.similarity_search(question, k=k, **search_kwargs)
        except Exception as exc:  # noqa: BLE001
            raise EmbeddingError(f"Searching the index failed: {_shorten(str(exc))}") from exc

    def answer(
        self,
        question: str,
        chat_history: list[dict] | None = None,
        sources: list[str] | None = None,
    ) -> RAGResult:
        """Answer a question using only retrieved chunks, with source citations."""
        question = question.strip()
        if not question:
            return RAGResult(answer="Please enter a question.", sources=[], found=False)

        retrieved = self.retrieve(question, sources=sources)
        if not retrieved:
            return RAGResult(answer=NOT_FOUND_MESSAGE, sources=[], found=False)

        answer = run_chain(
            RAG_QA_PROMPT,
            {
                "chat_history": _format_history(chat_history),
                "context": _format_context(retrieved),
                "question": question,
            },
        )

        if answer.strip().strip("*_\"' ").startswith(NOT_FOUND_MESSAGE):
            return RAGResult(answer=NOT_FOUND_MESSAGE, sources=[], found=False)

        # Show the sources the model cited; fall back to everything retrieved.
        cited = {n for n in _cited_numbers(answer) if 1 <= n <= len(retrieved)}
        wanted = cited or set(range(1, len(retrieved) + 1))

        references: list[SourceReference] = []
        for number, doc in enumerate(retrieved, start=1):
            if number in wanted:
                references.append(
                    SourceReference(
                        index=number,
                        filename=str(doc.metadata.get("source", "unknown")),
                        page=int(doc.metadata.get("page", 0)),
                        snippet=_make_snippet(doc.page_content),
                    )
                )
        return RAGResult(answer=answer, sources=references, found=True)